@echo off
rem Auto-generated by SnakeFlow. Triggers Quality Hub via agent-loop IPC.
set "DIR=%~dp0"
if "%DIR:~-1%"=="\" set "DIR=%DIR:~0,-1%"
node -e "const fs=require('fs'),p=require('path');const d=process.argv[1];fs.mkdirSync(d,{recursive:true});fs.writeFileSync(p.join(d,'trigger-run.json'),JSON.stringify({kind:'quality',scope:'workspace',ts:Date.now()},null,2))" "%DIR%"
if errorlevel 1 exit /b 1
